package com.ranchosoftware.ranchobleexample2.utility;

import java.util.HashMap;

public class CompanyIdentifiers {

  static HashMap<Integer, String> companies = new HashMap<Integer, String>();
  static {
    companies.put(  0,"Ericsson Technology Licensing");
    companies.put(  1,"Nokia Mobile Phones");
    companies.put(  2,"Intel Corp.");
    companies.put(  3,"IBM Corp.");
    companies.put(  4,"Toshiba Corp.");
    companies.put(  5,"3Com");
    companies.put(  6,"Microsoft");
    companies.put(  7,"Lucent");
    companies.put(  8,"Motorola");
    companies.put(  9,"Infineon Technologies AG");
    companies.put(  10 ,"Cambridge Silicon Radio");
    companies.put(  11 ,"Silicon Wave");
    companies.put(  12 ,"Digianswer A/S");
    companies.put(  13 ,"Texas Instruments Inc.");
    companies.put(  14 ,"Ceva, Inc. (formerly Parthus Technologies, Inc.)");
    companies.put(  15 ,"Broadcom Corporation");
    companies.put(  16 ,"Mitel Semiconductor");
    companies.put(  17 ,"Widcomm, Inc");
    companies.put(  18 ,"Zeevo, Inc.");
    companies.put(  19 ,"Atmel Corporation");
    companies.put(  20 ,"Mitsubishi Electric Corporation");
    companies.put(  21 ,"RTX Telecom A/S");
    companies.put(  22 ,"KC Technology Inc.");
    companies.put(  23 ,"NewLogic");
    companies.put(  24 ,"Transilica, Inc.");
    companies.put(  25 ,"Rohde & Schwarz GmbH & Co. KG");
    companies.put(  26 ,"TTPCom Limited");
    companies.put(  27 ,"Signia Technologies, Inc.");
    companies.put(  28 ,"Conexant Systems Inc.");
    companies.put(  29 ,"Qualcomm");
    companies.put(  30 ,"Inventel");
    companies.put(  31 ,"AVM Berlin");
    companies.put(  32 ,"BandSpeed, Inc.");
    companies.put(  33 ,"Mansella Ltd");
    companies.put(  34 ,"NEC Corporation");
    companies.put(  35 ,"WavePlus Technology Co., Ltd.");
    companies.put(  36 ,"Alcatel");
    companies.put(  37 ,"NXP Semiconductors (formerly Philips Semiconductors)");
    companies.put(  38 ,"C Technologies");
    companies.put(  39 ,"Open Interface");
    companies.put(  40 ,"R F Micro Devices");
    companies.put(  41 ,"Hitachi Ltd");
    companies.put(  42 ,"Symbol Technologies, Inc.");
    companies.put(  43 ,"Tenovis");
    companies.put(  44 ,"Macronix International Co. Ltd.");
    companies.put(  45 ,"GCT Semiconductor");
    companies.put(  46 ,"Norwood Systems");
    companies.put(  47 ,"MewTel Technology Inc.");
    companies.put(  48 ,"ST Microelectronics");
    companies.put(  49 ,"Synopsis");
    companies.put(  50 ,"Red-M (Communications) Ltd");
    companies.put(  51 ,"Commil Ltd");
    companies.put(  52 ,"Computer Access Technology Corporation (CATC)");
    companies.put(  53 ,"Eclipse (HQ Espana) S.L.");
    companies.put(  54 ,"Renesas Electronics Corporation");
    companies.put(  55 ,"Mobilian Corporation");
    companies.put(  56 ,"Terax");
    companies.put(  57 ,"Integrated System Solution Corp.");
    companies.put(  58 ,"Matsushita Electric Industrial Co., Ltd.");
    companies.put(  59 ,"Gennum Corporation");
    companies.put(  60 ,"BlackBerry Limited (formerly Research In Motion)");
    companies.put(  61 ,"IPextreme, Inc.");
    companies.put(  62 ,"Systems and Chips, Inc.");
    companies.put(  63 ,"Bluetooth SIG, Inc.");
    companies.put(  64 ,"Seiko Epson Corporation");
    companies.put(  65 ,"Integrated Silicon Solution Taiwan, Inc.");
    companies.put(  66 ,"CONWISE Technology Corporation Ltd");
    companies.put(  67 ,"PARROT SA");
    companies.put(  68 ,"Socket Mobile");
    companies.put(  69 ,"Atheros Communications, Inc.");
    companies.put(  70 ,"MediaTek, Inc.");
    companies.put(  71 ,"Bluegiga");
    companies.put(  72 ,"Marvell Technology Group Ltd.");
    companies.put(  73 ,"3DSP Corporation");
    companies.put(  74 ,"Accel Semiconductor Ltd.");
    companies.put(  75 ,"Continental Automotive Systems");
    companies.put(  76 ,"Apple, Inc.");
    companies.put(  77 ,"Staccato Communications, Inc.");
    companies.put(  78 ,"Avago Technologies");
    companies.put(  79 ,"APT Licensing Ltd.");
    companies.put(  80 ,"SiRF Technology");
    companies.put(  81 ,"Tzero Technologies, Inc.");
    companies.put(  82 ,"J&M Corporation");
    companies.put(  83 ,"Free2move AB");
    companies.put(  84 ,"3DiJoy Corporation");
    companies.put(  85 ,"Plantronics, Inc.");
    companies.put(  86 ,"Sony Ericsson Mobile Communications");
    companies.put(  87 ,"Harman International Industries, Inc.");
    companies.put(  88 ,"Vizio, Inc.");
    companies.put(  89 ,"Nordic Semiconductor ASA");
    companies.put(  90 ,"EM Microelectronic-Marin SA");
    companies.put(  91 ,"Ralink Technology Corporation");
    companies.put(  92 ,"Belkin International, Inc.");
    companies.put(  93 ,"Realtek Semiconductor Corporation");
    companies.put(  94 ,"Stonestreet One, LLC");
    companies.put(  95 ,"Wicentric, Inc.");
    companies.put(  96 ,"RivieraWaves S.A.S");
    companies.put(  97 ,"RDA Microelectronics");
    companies.put(  98 ,"Gibson Guitars");
    companies.put(  99 ,"MiCommand Inc.");
    companies.put(  100,"Band XI International, LLC");
    companies.put(  101,"Hewlett-Packard Company");
    companies.put(  102,"9Solutions Oy");
    companies.put(  103,"GN Netcom A/S");
    companies.put(  104,"General Motors");
    companies.put(  105,"A&D Engineering, Inc.");
    companies.put(  106,"MindTree Ltd.");
    companies.put(  107,"Polar Electro OY");
    companies.put(  108,"Beautiful Enterprise Co., Ltd.");
    companies.put(  109,"BriarTek, Inc.");
    companies.put(  110,"Summit Data Communications, Inc.");
    companies.put(  111,"Sound ID");
    companies.put(  112,"Monster, LLC");
    companies.put(  113,"connectBlue AB");
    companies.put(  114,"ShangHai Super Smart Electronics Co. Ltd.");
    companies.put(  115,"Group Sense Ltd.");
    companies.put(  116,"Zomm, LLC");
    companies.put(  117,"Samsung Electronics Co. Ltd.");
    companies.put(  118,"Creative Technology Ltd.");
    companies.put(  119,"Laird Technologies");
    companies.put(  120,"Nike, Inc.");
    companies.put(  121,"lesswire AG");
    companies.put(  122,"MStar Semiconductor, Inc.");
    companies.put(  123,"Hanlynn Technologies");
    companies.put(  124,"A & R Cambridge");
    companies.put(  125,"Seers Technology Co. Ltd");
    companies.put(  126,"Sports Tracking Technologies Ltd.");
    companies.put(  127,"Autonet Mobile");
    companies.put(  128,"DeLorme Publishing Company, Inc.");
    companies.put(  129,"WuXi Vimicro");
    companies.put(  130,"Sennheiser Communications A/S");
    companies.put(  131,"TimeKeeping Systems, Inc.");
    companies.put(  132,"Ludus Helsinki Ltd.");
    companies.put(  133,"BlueRadios, Inc.");
    companies.put(  134,"equinox AG");
    companies.put(  135,"Garmin International, Inc.");
    companies.put(  136,"Ecotest");
    companies.put(  137,"GN ReSound A/S");
    companies.put(  138,"Jawbone");
    companies.put(  139,"Topcorn Positioning Systems, LLC");
    companies.put(  140,"Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)​​");
    companies.put(  141,"Zscan Software");
    companies.put(  142,"Quintic Corp.");
    companies.put(  143,"Stollman E+V GmbH");
    companies.put(  144,"Funai Electric Co., Ltd.");
    companies.put(  145,"Advanced PANMOBIL Systems GmbH & Co. KG");
    companies.put(  146,"ThinkOptics, Inc.");
    companies.put(  147,"Universal Electronics, Inc.");
    companies.put(  148,"Airoha Technology Corp.");
    companies.put(  149,"NEC Lighting, Ltd.");
    companies.put(  150,"ODM Technology, Inc.");
    companies.put(  151,"ConnecteDevice Ltd.");
    companies.put(  152,"zer01.tv GmbH");
    companies.put(  153,"i.Tech Dynamic Global Distribution Ltd.");
    companies.put(  154,"Alpwise");
    companies.put(  155,"Jiangsu Toppower Automotive Electronics Co., Ltd.");
    companies.put(  156,"Colorfy, Inc.");
    companies.put(  157,"Geoforce Inc.");
    companies.put(  158,"Bose Corporation");
    companies.put(  159,"Suunto Oy");
    companies.put(  160,"Kensington Computer Products Group");
    companies.put(  161,"SR-Medizinelektronik");
    companies.put(  162,"Vertu Corporation Limited");
    companies.put(  163,"Meta Watch Ltd.");
    companies.put(  164,"LINAK A/S");
    companies.put(  165,"OTL Dynamics LLC");
    companies.put(  166,"Panda Ocean Inc.");
    companies.put(  167,"Visteon Corporation");
    companies.put(  168,"ARP Devices Limited");
    companies.put(  169,"Magneti Marelli S.p.A");
    companies.put(  170,"CAEN RFID srl");
    companies.put(  171,"Ingenieur-Systemgruppe Zahn GmbH");
    companies.put(  172,"Green Throttle Games");
    companies.put(  173,"Peter Systemtechnik GmbH");
    companies.put(  174,"Omegawave Oy");
    companies.put(  175,"Cinetix");
    companies.put(  176,"Passif Semiconductor Corp");
    companies.put(  177,"Saris Cycling Group, Inc");
    companies.put(  178,"​Bekey A/S");
    companies.put(  179,"​Clarinox Technologies Pty. Ltd.");
    companies.put(  180,"​BDE Technology Co., Ltd.");
    companies.put(  181,"Swirl Networks");
    companies.put(  182,"​Meso international");
    companies.put(  183,"​TreLab Ltd");
    companies.put(  184,"​Qualcomm Innovation Center, Inc. (QuIC)");
    companies.put(  185,"​​Johnson Controls, Inc.");
    companies.put(  186,"​Starkey Laboratories Inc.");
    companies.put(  187,"​​S-Power Electronics Limited");
    companies.put(  188,"​​Ace Sensor Inc");
    companies.put(  189,"​​Aplix Corporation");
    companies.put(  190,"​​AAMP of America");
    companies.put(  191,"​​Stalmart Technology Limited");
    companies.put(  192,"​​AMICCOM Electronics Corporation");
    companies.put(  193,"​​Shenzhen Excelsecu Data Technology Co.,Ltd");
    companies.put(  194,"​​Geneq Inc.");
    companies.put(  195,"​​adidas AG");
    companies.put(  196,"​​LG Electronics​");

    companies.put(  197 , "Onset Computer Corporation");
    companies.put(  198 , "Selfly BV");
    companies.put(  199 , "Quuppa Oy.");
    companies.put(  200 , "GeLo Inc");
    companies.put(  201 , "Evluma");
    companies.put(  202 , "MC10");
    companies.put(  203 , "Binauric SE");
    companies.put(  204 , "Beats Electronics");
    companies.put(  205 , "Microchip Technology Inc.");
    companies.put(  206 , "Elgato Systems GmbH");
    companies.put(  207 , "ARCHOS SA");
    companies.put(  208 , "Dexcom, Inc.");
    companies.put(  209 , "Polar Electro Europe B.V.");
    companies.put(  210 , "Dialog Semiconductor B.V.");
    companies.put(  211 , "Taixingbang Technology (HK) Co,. LTD.");
    companies.put(  212 , "Kawantech");
    companies.put(  213 , "Austco Communication Systems");
    companies.put(  214 , "Timex Group USA, Inc.");
    companies.put(  215 , "Qualcomm Technologies, Inc.");
    companies.put(  216 , "Qualcomm Connected Experiences, Inc.");
    companies.put(  217 , "Voyetra Turtle Beach");
    companies.put(  218 , "txtr GmbH");
    companies.put(  219 , "Biosentronics");
    companies.put(  220 , "Procter & Gamble");
    companies.put(  221 , "Hosiden Corporation");
    companies.put(  222 , "Muzik LLC");
    companies.put(  223 , "Misfit Wearables Corp");
    companies.put(  224 , "Google");
    companies.put(  225 , "Danlers Ltd");
    companies.put(  226 , "Semilink Inc");
    companies.put(  227 , "inMusic Brands, Inc");
    companies.put(  228 , "L.S. Research Inc.");
    companies.put(  229 , "Eden Software Consultants Ltd.");
    companies.put(  230 , "Freshtemp");
    companies.put(  231 , "KS Technologies");
    companies.put(  232 , "ACTS Technologies");
    companies.put(  233 , "Vtrack Systems");
    companies.put(  234 , "Nielsen-Kellerman Company");
    companies.put(  235 , "Server Technology, Inc.");
    companies.put(  236 , "BioResearch Associates");
    companies.put(  237 , "Jolly Logic, LLC");
    companies.put(  238 , "Above Average Outcomes, Inc.");
    companies.put(  239 , "Bitsplitters GmbH");
    companies.put(  240 , "PayPal, Inc.");
    companies.put(  241 , "Witron Technology Limited");
    companies.put(  242 , "Aether Things Inc. (formerly Morse Project Inc.)");
    companies.put(  243 , "Kent Displays Inc.");
    companies.put(  244 , "Nautilus Inc.");
    companies.put(  245 , "Smartifier Oy");
    companies.put(  246 , "Elcometer Limited");
    companies.put(  247 , "VSN Technologies Inc.");
    companies.put(  248 , "AceUni Corp., Ltd.");
    companies.put(  249 , "StickNFind");
    companies.put(  250 , "Crystal Code AB");
    companies.put(  251 , "KOUKAAM a.s.");
    companies.put(  252 , "Delphi Corporation");
    companies.put(  253 , "ValenceTech Limited");
    companies.put(  254 , "Reserved");
    companies.put(  255 , "Typo Products, LLC");
    companies.put(  256 , "TomTom International BV");
    companies.put(  257 , "Fugoo, Inc");
    companies.put(  258 , "Keiser Corporation");
    companies.put(  259 , "Bang & Olufsen A/S");
    companies.put(  260 , "PLUS Locations Systems Pty Ltd");
    companies.put(  261 , "Ubiquitous Computing Technology Corporation");
    companies.put(  262 , "Innovative Yachtter Solutions");
    companies.put(  263 , "William Demant Holding A/S");
    companies.put(  264 , "Chicony Electronics Co., Ltd.");
    companies.put(  265 , "Atus BV");
    companies.put(  266 , "Codegate Ltd.");
    companies.put(  267 , "ERi, Inc.");
    companies.put(  268 , "Transducers Direct, LLC");
    companies.put(  269 , "Fujitsu Ten Limited");
    companies.put(  270 , "Audi AG");
    companies.put(  271 , "HiSilicon Technologies Co., Ltd.");
    companies.put(  272 , "Nippon Seiki Co., Ltd.");
    companies.put(  273 , "Steelseries ApS");
    companies.put(  274 , "vyzybl Inc.");
    companies.put(  275 , "Openbrain Technologies, Co., Ltd.");
    companies.put(  276 , "Xensr");
    companies.put(  277 , "e.solutions");
    companies.put(  278 , "1OAK Technologies");
    companies.put(  279 , "Wimoto Technologies Inc");
    companies.put(  280 , "Radius Networks, Inc.");
    companies.put(  281 , "Wize Technology Co., Ltd.");
    companies.put(  282 , "Qualcomm Labs, Inc.");
    companies.put(  283 , "Aruba Networks");
    companies.put(  284 , "Baidu");
    companies.put(  285 , "Arendi AG");
    companies.put(  286 , "Skoda Auto a.s.");
    companies.put(  287 , "Volkswagon AG");
    companies.put(  288 , "Porsche AG");
    companies.put(  289 , "Sino Wealth Electronic Ltd.");
    companies.put(  290 , "AirTurn, Inc.");
    companies.put(  291 , "Kinsa, Inc.");
    companies.put(  292 , "HID Global");
    companies.put(  293 , "SEAT es");
    companies.put(  294 , "Promethean Ltd.");
    companies.put(  295 , "Salutica Allied Solutions");
    companies.put(  296 , "GPSI Group Pty Ltd");
    companies.put(  297 , "Nimble Devices Oy");
    companies.put(  298 , "Changzhou Yongse Infotech Co., Ltd");
    companies.put(  299 , "SportIQ");
    companies.put(  300 , "TEMEC Instruments B.V.");
    companies.put(  301 , "Sony Corporation");
    companies.put(  302 , "ASSA ABLOY");
    companies.put(  303 , "Clarion Co., Ltd.");
    companies.put(  304 , "Warehouse Innovations");
    companies.put(  305 , "Cypress Semiconductor Corporation");
    companies.put(  306 , "MADS Inc");
    companies.put(  307 , "Blue Maestro Limited");
    companies.put(  308 , "Resolution Products, Inc.");
    companies.put(  309 , "Airewear LLC");
    companies.put(  310 , "Seed Labs, Inc. (formerly ETC sp. z.o.o.)");
    companies.put(  311 , "Prestigio Plaza Ltd.");
    companies.put(  312 , "NTEO Inc.");
    companies.put(  313 , "Focus Systems Corporation");
    companies.put(  314 , "Tencent Holdings Limited");
    companies.put(  315 , "Allegion");
    companies.put(  316 , "Murata Manufacuring Co., Ltd.");
    companies.put(  318 , "Nod, Inc.");
    companies.put(  319 , "B&B Manufacturing Company");
    companies.put(  320 , "Alpine Electronics (China) Co., Ltd");
    companies.put(  321 , "FedEx Services");
    companies.put(  322 , "Grape Systems Inc.");
    companies.put(  323 , "Bkon Connect");
    companies.put(  324 , "Lintech GmbH");
    companies.put(  325 , "Novatel Wireless");
    companies.put(  326 , "Ciright");
    companies.put(  327 , "Mighty Cast, Inc.");
    companies.put(  328 , "Ambimat Electronics");
    companies.put(  329 , "Perytons Ltd.");
    companies.put(  330 , "Tivoli Audio, LLC");
    companies.put(  331 , "Master Lock");
    companies.put(  332 , "Mesh-Net Ltd");
    companies.put(  333 , "Huizhou Desay SV Automotive CO., LTD.");
    companies.put(  334 , "Tangerine, Inc.");
    companies.put(  335 , "B&W Group Ltd.");
    companies.put(  336 , "Pioneer Corporation");
    companies.put(  337 , "OnBeep");
    companies.put(  338 , "Vernier Software & Technology");
    companies.put(  339 , "ROL Ergo");
    companies.put(  340 , "Pebble Technology");
    companies.put(  341 , "NETATMO");
    companies.put(  342 , "Accumulate AB");
    companies.put(  343 , "Anhui Huami Information Technology Co., Ltd.");
    companies.put(  344 , "Inmite s.r.o.");
    companies.put(  345 , "ChefSteps, Inc.");
    companies.put(  346 , "micas AG");
    companies.put(  347 , "Biomedical Research Ltd.");
    companies.put(  348 , "Pitius Tec S.L.");
    companies.put(  349 , "Estimote, Inc.");
    companies.put(  350 , "Unikey Technologies, Inc.");
    companies.put(  351 , "Timer Cap Co.");
    companies.put(  352 , "AwoX");
    companies.put(  353 , "yikes");
    companies.put(  354 , "MADSGlobal NZ Ltd.");
    companies.put(  355 , "PCH International");
    companies.put(  356 , "Qingdao Yeelink Information Technology Co., Ltd.");
    companies.put(  357 , "Milwaukee Tool (formerly Milwaukee Electric Tools)");
    companies.put(  358 , "MISHIK Pte Ltd");
    companies.put(  359 , "Bayer HealthCare");
    companies.put(  360 , "Spicebox LLC");
    companies.put(  361 , "emberlight");
    companies.put(  362 , "Cooper-Atkins Corporation");
    companies.put(  363 , "Qblinks");
    companies.put(  364 , "MYSPHERA");
    companies.put(  365 , "LifeScan Inc");
    companies.put(  366 , "Volantic AB");
    companies.put(  367 , "Podo Labs, Inc");
    companies.put(  368 , "Roche Diabetes Care AG");
    companies.put(  369 , "Amazon Fulfillment Service");
    companies.put(  370 , "Connovate Technology Private Limited");
    companies.put(  371 , "Kocomojo, LLC");
    companies.put(  372 , "Everykey LLC");
    companies.put(  373 , "Dynamic Controls");
    companies.put(  374 , "SentriLock");
    companies.put(  375 , "I-SYST inc.");
    companies.put(  376 , "CASIO COMPUTER CO., LTD.");
    companies.put(  377 , "LAPIS Semiconductor Co., Ltd.");
    companies.put(  378 , "Telemonitor, Inc.");
    companies.put(  379 , "taskit GmbH");
    companies.put(  380 , "Daimler AG");
    companies.put(  381 , "BatAndCat");
    companies.put(  382 , "BluDotz Ltd");
    companies.put(  383 , "XTel ApS");
    companies.put(  384 , "Gigaset Communications GmbH");
    companies.put(  385 , "Gecko Health Innovations, Inc.");
    companies.put(  386 , "HOP Ubiquitous");
    companies.put(  387 , "To Be Assigned");
    companies.put(  388 , "Nectar");
    companies.put(  389 , "bel'apps LLC");
    companies.put(  390 , "CORE Lighting Ltd");
    companies.put(  391 , "Seraphim Sense Ltd");
    companies.put(  392 , "Unico RBC");
    companies.put(  393 , "Physical Enterprises Inc.");
    companies.put(  394 , "Able Trend Technology Limited");
    companies.put(  395 , "Konica Minolta, Inc.");
    companies.put(  396 , "Wilo SE");
    companies.put(  397 , "Extron Design Services");
    companies.put(  398 , "Fitbit, Inc.");
    companies.put(  399 , "Fireflies Systems");
    companies.put(  400 , "Intelletto Technologies Inc.");
    companies.put(  401 , "FDK CORPORATION");
    companies.put(  402 , "Cloudleaf, Inc");
    companies.put(  403 , "Maveric Automation LLC");
    companies.put(  404 , "Acoustic Stream Corporation");
    companies.put(  05  , "Zuli");
    companies.put(  406 , "Paxton Access Ltd");
    companies.put(  407 , "WiSilica Inc");
    companies.put(  408 , "Vengit Limited");
    companies.put(  409 , "SALTO SYSTEMS S.L.");
    companies.put(  410 , "T-Engine Forum");
    companies.put(  411 , "CUBETECH s.r.o.");
    companies.put(  412 , "Cokiya Incorporated");
    companies.put(  413 , "CVS Health");
    companies.put(  414 , "Ceruus");
    companies.put(  415 , "Strainstall Ltd");
    companies.put(  416 , "Channel Enterprises (HK) Ltd.");
    companies.put(  417 , "FIAMM");
    companies.put(  418 , "GIGALANE.CO.,LTD");
    companies.put(  419 , "EROAD");
    companies.put(  420 , "Mine Safety Appliances");
    companies.put(  421 , "Icon Health and Fitness");
    companies.put(  422 , "Asandoo GmbH");
    companies.put(  423 , "ENERGOUS CORPORATION");
    companies.put(  424 , "Taobao");
    companies.put(  425 , "Canon Inc.");
    companies.put(  426 , "Geophysical Technology Inc.");
    companies.put(  427 , "Facebook, Inc.");
    companies.put(  428 , "Nipro Diagnostics, Inc.");
    companies.put(  429 , "FlightSafety International");
    companies.put(  430 , "Earlens Corporation");
    companies.put(  431 , "Sunrise Micro Devices, Inc.");
    companies.put(  432 , "Star Micronics Co., Ltd.");
    companies.put(  433 , "Netizens Sp. z o.o.");

  }

  public static String companyNameFromCode(int code){
    if (companies.containsKey(code))
      return companies.get(code);

    return "unknown";
  }


}
